version: 1.2.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
- Ubuntu1804
- macos-mojave
configuration: Release
platform:
- x64
- x86
cache:
- externals/OpenSceneGraph
- resources/models

after_build:
 - 
  cmd:
    7z a esmini-bin.zip bin/*

    appveyor PushArtifact esmini-bin.zip

for:
  -
    matrix:
      only:
        - image: Ubuntu1804
    build_script:
      - echo Ubuntu build script
      - sh: >-
          sudo apt install build-essential git pkg-config libgl1-mesa-dev libpthread-stubs0-dev libjpeg-dev libxml2-dev libpng-dev libtiff5-dev libgdal-dev libpoppler-dev libdcmtk-dev libgstreamer1.0-dev libgtk2.0-dev libcairo2-dev libpoppler-glib-dev libxrandr-dev libxinerama-dev curl cmake

          mkdir build

          cd build

          cmake ../ -DUSE_OSG=false

          make -j4
          
    after_build:
      - sh: >-
          zip esmini-bin.zip EnvironmentSimulator/RoadManagerDLL/libRoadManagerDLL.so EnvironmentSimulator/ScenarioEngineDLL/libScenarioEngineDLL.so
          
          appveyor PushArtifact esmini-bin.zip

  -
    matrix:
      only:
        - image: macos-mojave
    build_script:
      - echo MacOS Mojave build script
      - sh: >-
          chmod +x create_xcode_project.sh
          
          ./create_xcode_project.sh
          
          cd build
          
          xcodebuild -scheme install -configuration Release build

    after_build:
      - sh: >-
          lipo -create EnvironmentSimulator/RoadManagerDLL/Release/libRoadManagerDLL.dylib -output ../bin/RoadManagerDLL.bundle
          
          lipo -create EnvironmentSimulator/ScenarioEngineDLL/Release/libScenarioEngineDLL.dylib -output ../bin/ScenarioEngineDLL.bundle

          cd ..
          
          zip esmini-bin.zip bin -r
          
          appveyor PushArtifact esmini-bin.zip    
          
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64
    build_script:
      - echo Visual Studio 2017 x64 build script
      - cmd:
          mkdir buildVS15_64
          
          cd buildVS15_64
          
          cmake.exe -G "Visual Studio 15 Win64" -D USE_OSG=True ..
          
      - ps: |
          echo "const char* ESMINI_BUILD_VERSION=`"$env:APPVEYOR_BUILD_VERSION`";"  | Out-File ../EnvironmentSimulator/CommonMini/buildnr.cpp
          type ../EnvironmentSimulator/CommonMini/buildnr.cpp
          
      - cmd: 

          msbuild /m /property:Configuration=Release EnvironmentSimulator.sln

          cd..

          generate_binary_dist.bat

          7z a esmini-demo.zip esmini-demo/*

          appveyor PushArtifact esmini-demo.zip
  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x86
    build_script:
      - echo Visual Studio 2017 x86 build script
      - cmd:
          mkdir buildVS15_32

          cd buildVS15_32

          cmake -G "Visual Studio 15" -D USE_OSG=True ..

      - ps: |
          ((Get-Content -path ../EnvironmentSimulator/CommonMini/version.cpp -Raw) -replace 'TBD',"$env:APPVEYOR_BUILD_VERSION") | Set-Content -Path ../EnvironmentSimulator/CommonMini/version.cpp
          type ../EnvironmentSimulator/CommonMini/version.cpp

      - cmd:
          msbuild /m /property:Configuration=Release /p:Platform=win32 EnvironmentSimulator.sln

          cd..
  -
    matrix:
      only:
        - image: Visual Studio 2015
          platform: x64
    build_script:
      - echo Visual Studio 2015 x64 build script
      - cmd:
          mkdir buildVS14_winsdk71_64

          cd buildVS14_winsdk71_64

          cmake -G "Visual Studio 14 2015 Win64" -T "Windows7.1SDK" -D WINSDK7_1=True -D USE_OSG=True ..

      - ps: |
          ((Get-Content -path ../EnvironmentSimulator/CommonMini/version.cpp -Raw) -replace 'TBD',"$env:APPVEYOR_BUILD_VERSION") | Set-Content -Path ../EnvironmentSimulator/CommonMini/version.cpp
          type ../EnvironmentSimulator/CommonMini/version.cpp

      - cmd:
          msbuild /m /property:Configuration=Release EnvironmentSimulator.sln

          cd..
  -
    matrix:
      exclude:
        - image: Ubuntu1804
          platform: x86
        - image: macos-mojave
          platform: x86
        - image: Visual Studio 2015
          platform: x86
